apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  selector:
    matchLabels:
      name: python-pod
      app: python-demo-app
  template:
    metadata:
      labels:
        name: python-pod
        app: python-demo-app
    spec:
      containers:
      - name: myapp
        image: mostafaashour99/py-app:latest
        resources:
        ports:
        - containerPort: 8000
        env:
          - name: HOST
            value: localhost 
          - name: REDIS_HOST
            value: redis‏
     
